export enum CategoryActions{
    CATEGORY_ADD = 'CATEGORY_ADD',
    CATEGORY_CHANGE = 'CATEGORY_CHANGE',
    CATEGORY_EDIT = 'CATEGORY_EDIT',
    CATEGORY_DELETE = 'CATEGORY_DELETE',
    CATEGORY_CLEAR = 'CATEGORY_CLEAR'
}
